import { mdas } from "../admin/data";
import stateAndLga from "./stateAndLga.json";

export const HEADER_MAP = {
  "IPPIS Number": "ippisNumber",
  "Name (Surname, First Name)": "fullName",
  DOB: "dateOfBirth",
  Gender: "gender",
  "State of Origin": "stateOfOrigin",
  "Local Government Area": "lga",
  "Pool Office": "poolOffice",
  "Current MDA": "currentMDA",
  Cadre: "cadre",
  "Grade Level": "gradeLevel",
  "Date of First Appointment": "dateOfFirstAppointment",
  "Date of Confirmation": "dateOfConfirmation",
  "Date of Last Promotion": "dateOfLastPromotion",
  "Phone Number": "phoneNumber",
  Email: "email",
  "State of Current Posting": "stateOfCurrentPosting",
  2021: "year2021",
  2022: "year2022",
  2023: "year2023",
  2024: "year2024",
  Remark: "remark",
};

const genders = ["Male", "Female"];
const gradeLevel = Array.from({ length: 16 }, (_, i) => i + 1);
export const headerMap = [
  {
    field: "ippisNumber",
    label: "IPPIS Number",
    minWidth: 100,
    align: "left",
    type: "text",
    format: (value) => value,
  },
  {
    field: "fullName",
    label: "Full Name",
    minWidth: 100,
    align: "left",
    type: "text",
    format: (value) => value,
  },
  {
    field: "dateOfBirth",
    label: "Date of Birth",
    minWidth: 100,
    align: "left",
    type: "date",
    format: (value) => new Date(value).toLocaleDateString(),
  },
  {
    field: "gender",
    label: "Gender",
    minWidth: 100,
    align: "left",
    type: "dropdown",
    data: genders,
    format: (value) => value,
  },
  {
    field: "stateOfOrigin",
    label: "State of Origin",
    minWidth: 100,
    align: "left",
    type: "dropdown",
    data: stateAndLga.map((c) => c.name),
    format: (value) => value,
  },
  {
    field: "lga",
    label: "Local Government Area",
    minWidth: 100,
    align: "left",
    type: "dropdown",
    filter: "stateOfOrigin",
    data: (filter) =>
      stateAndLga.filter(
        (c) => c.name.toLowerCase() === filter.toLowerCase()
      )[0].local_government_areas,
    // .map((c) => c.local_government_areas),
    format: (value) => value,
  },
  {
    field: "poolOffice",
    label: "Pool Office",
    minWidth: 100,
    align: "left",
    type: "text",
    format: (value) => value,
  },
  {
    field: "currentMDA",
    label: "Current MDA",
    minWidth: 100,
    align: "left",
    type: "dropdown",
    data: mdas,
    format: (value) => value,
  },
  {
    field: "cadre",
    label: "Cadre",
    minWidth: 100,
    align: "left",
    type: "text",
    format: (value) => value,
  },
  {
    field: "gradeLevel",
    label: "Grade Level",
    minWidth: 100,
    align: "left",
    type: "dropdown",
    data: gradeLevel,
    format: (value) => value,
  },
  {
    field: "dateOfFirstAppointment",
    label: "Date of First Appointment",
    minWidth: 100,
    align: "left",
    type: "date",
    format: (value) => new Date(value).toLocaleDateString(),
  },
  {
    field: "dateOfConfirmation",
    label: "Date of Confirmation",
    minWidth: 100,
    align: "left",
    type: "date",
    format: (value) => new Date(value).toLocaleDateString(),
  },
  {
    field: "dateOfLastPromotion",
    label: "Date of Last Promotion",
    minWidth: 100,
    align: "left",
    type: "date",
    format: (value) => new Date(value).toLocaleDateString(),
  },
  {
    field: "phoneNumber",
    label: "Phone Number",
    minWidth: 100,
    align: "left",
    format: (value) => value,
  },
  {
    field: "email",
    label: "Email",
    minWidth: 100,
    align: "left",
    type: "text",
    format: (value) => value,
  },
  {
    field: "stateOfCurrentPosting",
    label: "State of Current Posting",
    minWidth: 100,
    align: "left",
    type: "dropdown",
    data: stateAndLga.map((c) => c.name),
    format: (value) => value,
  },
];
