export const mdas = [
  "FED. MIN. OF INFORMATION & NATIONAL ORIENTATION",
  "FED. MIN. OF LABOUR & EMPLOYMENT",
  "FED. MIN. OF LIVESTOCK DEVELOPMENT",
  "FED. MIN. OF YOUTH DEVELOPMENT",
  "OFFICE OF THE ACCOUNTANT GENERAL OF THE FEDERATION",
  "FED. MIN. OF EDUCATION",
  "OFFICE OF THE HEAD OF THE CIVIL SERVICE OF THE FEDERATION",
  "FED. MIN. OF ENVIRONMENT",
  "NATIONAL SPORTS COMMISSION",
  "FED. MIN. OF HUMANITARIAN AFFAIRS & POVERTY ALLEVIATION ",
  "FED. MIN. OF ARTS, CULTURE & CREATIVE ECONOMY",
  "FED. MIN. OF FINANCE",
  "FED. MIN. OF POWER",
  "FED. MIN. OF INNOVATION, SCIENCE & TECHNOLOGY",
  "OFFICE OF THE SURVEYOR GENERAL OF THE FEDERATION",
  "MIN. OF REGIONAL DEVELOPMENT",
  "FED. MIN. OF INDUSTRY, TRADE & INVESTMENT",
  "OFFICE OF THE AUDITOR GENERAL FOR THE FEDERATION",
  "FED. MIN. OF WOMEN AFFAIRS",
  "MIN. OF DEFENCE",
  "MIN. OF SOLID MINIRALS DEVELOPMENT",
  "FED. MIN. OF COMMUNICATIONS, INNOVATION & DIGITAL ECONOMY",
  "FED. MIN. OF TRANSPORTATION",
  "MIN. OF STEEL DEVELOPMENT",
  "FED. MIN. OF HOUSING & URBAN DEVELOPMENT",
  "MIN. OF POLICE AFFAIRS",
  "FED. MIN. OF JUSTICE",
  "MIN. OF PETROLEUM RESOURCES",
  "FED. MIN. OF AVIATION & AEROSPACE DEVELOPMENT",
  "MIN. OF FOREIGN AFFAIRS",
  "FED. MIN. OF WATER RESOURCES & SANITATION",
  "FED. MIN. OF HEALTH & SOCIAL WELFARE",
  "FED. MIN. OF BUDGET & ECONOMIC PLANNING",
  "FED. MIN. OF AGRICULTURE & FOOD SECURITY",
  "FED. MIN. OF MARINE & BLUE ECONOMY",
  "FED. MIN. OF WORKS",
  "STATE HOUSE",
].sort();

const stateAndLgas = [
  {
    state: "abia",
    lgas: [
      "aba north",
      "aba south",
      "arochukwu",
      "bende",
      "ikwuano",
      "isiala ngwa north",
      "isiala ngwa south",
      "isuikwuato",
      "obi ngwa",
      "ohafia",
      "osisioma",
      "ugwunagbo",
      "ukwa east",
      "ukwa west",
      "umuahia north",
      "umuahia south",
      "umu nneochi",
    ],
  },
  {
    state: "adamawa",
    lgas: [
      "demsa",
      "fufure",
      "ganye",
      "gayuk",
      "gombi",
      "grie",
      "hong",
      "jada",
      "larmurde",
      "madagali",
      "maiha",
      "mayo belwa",
      "michika",
      "mubi north",
      "mubi south",
      "numan",
      "shelleng",
      "song",
      "toungo",
      "yola north",
      "yola south",
    ],
  },
  {
    state: "akwa ibom",
    lgas: [
      "abak",
      "eastern obolo",
      "eket",
      "esit eket",
      "essien udim",
      "etim ekpo",
      "etinan",
      "ibeno",
      "ibesikpo asutan",
      "ibiono-ibom",
      "ika",
      "ikono",
      "ikot abasi",
      "ikot ekpene",
      "ini",
      "itu",
      "mbo",
      "mkpat-enin",
      "nsit-atai",
      "nsit-ibom",
      "nsit-ubium",
      "obot akara",
      "okobo",
      "onna",
      "oron",
      "oruk anam",
      "udung-uko",
      "ukanafun",
      "uruan",
      "urue-offong/oruko",
      "uyo",
    ],
  },
  {
    state: "anambra",
    lgas: [
      "aguata",
      "anambra east",
      "anambra west",
      "anaocha",
      "awka north",
      "awka south",
      "ayamelum",
      "dunukofia",
      "ekwusigo",
      "idemili north",
      "idemili south",
      "ihiala",
      "njikoka",
      "nnewi north",
      "nnewi south",
      "ogbaru",
      "onitsha north",
      "onitsha south",
      "orumba north",
      "orumba south",
      "oyi",
    ],
  },
  {
    state: "bauchi",
    lgas: [
      "alkaleri",
      "bauchi",
      "bogoro",
      "damban",
      "darazo",
      "dass",
      "gamawa",
      "ganjuwa",
      "giade",
      "itas/gadau",
      "jama'are",
      "katagum",
      "kirfi",
      "misau",
      "ningi",
      "shira",
      "tafawa balewa",
      "toro",
      "warji",
      "zaki",
    ],
  },
  {
    state: "bayelsa",
    lgas: [
      "brass",
      "ekeremor",
      "kolokuma/opokuma",
      "nembe",
      "ogbia",
      "sagbama",
      "southern ijaw",
      "yenagoa",
    ],
  },
  {
    state: "benue",
    lgas: [
      "agatu",
      "apa",
      "ado",
      "buruku",
      "gboko",
      "guma",
      "gwer east",
      "gwer west",
      "katsina-ala",
      "konshisha",
      "kwande",
      "logo",
      "makurdi",
      "obi",
      "ogbadibo",
      "ohimini",
      "oju",
      "okpokwu",
      "oturkpo",
      "tarka",
      "ukum",
      "ushongo",
      "vandeikya",
    ],
  },
  {
    state: "borno",
    lgas: [
      "abadam",
      "askira/uba",
      "bama",
      "bayo",
      "biu",
      "chibok",
      "damboa",
      "dikwa",
      "gubio",
      "guzamala",
      "gwoza",
      "hawul",
      "jere",
      "kaga",
      "kala/balge",
      "konduga",
      "kukawa",
      "kwaya kusar",
      "mafa",
      "magumeri",
      "maiduguri",
      "marte",
      "mobbar",
      "monguno",
      "ngala",
      "nganzai",
      "shani",
    ],
  },
  {
    state: "cross river",
    lgas: [
      "abi",
      "akamkpa",
      "akpabuyo",
      "bakassi",
      "bekwarra",
      "biase",
      "boki",
      "calabar municipal",
      "calabar south",
      "etung",
      "ikom",
      "obanliku",
      "obubra",
      "obudu",
      "odukpani",
      "ogoja",
      "yakuur",
      "yala",
    ],
  },
  {
    state: "delta",
    lgas: [
      "aniocha north",
      "aniocha south",
      "bomadi",
      "burutu",
      "ethiope east",
      "ethiope west",
      "ika north east",
      "ika south",
      "isoko north",
      "isoko south",
      "ndokwa east",
      "ndokwa west",
      "okpe",
      "oshimili north",
      "oshimili south",
      "patani",
      "sapele, delta",
      "udu",
      "ughelli north",
      "ughelli south",
      "ukwuani",
      "uvwie",
      "warri north",
      "warri south",
      "warri south west",
    ],
  },
  {
    state: "ebonyi",
    lgas: [
      "abakaliki",
      "afikpo north",
      "afikpo south",
      "ebonyi",
      "ezza north",
      "ezza south",
      "ikwo",
      "ishielu",
      "ivo",
      "izzi",
      "ohaozara",
      "ohaukwu",
      "onicha",
    ],
  },
  {
    state: "edo",
    lgas: [
      "akoko-edo",
      "egor",
      "esan central",
      "esan north-east",
      "esan south-east",
      "esan west",
      "etsako central",
      "etsako east",
      "etsako west",
      "igueben",
      "ikpoba okha",
      "orhionmwon",
      "oredo",
      "ovia north-east",
      "ovia south-west",
      "owan east",
      "owan west",
      "uhunmwonde",
    ],
  },
  {
    state: "ekiti",
    lgas: [
      "ado ekiti",
      "efon",
      "ekiti east",
      "ekiti south-west",
      "ekiti west",
      "emure",
      "gbonyin",
      "ido osi",
      "ijero",
      "ikere",
      "ikole",
      "ilejemeje",
      "irepodun/ifelodun",
      "ise/orun",
      "moba",
      "oye",
    ],
  },
  {
    state: "enugu",
    lgas: [
      "aninri",
      "awgu",
      "enugu east",
      "enugu north",
      "enugu south",
      "ezeagu",
      "igbo etiti",
      "igbo eze north",
      "igbo eze south",
      "isi uzo",
      "nkanu east",
      "nkanu west",
      "nsukka",
      "oji river",
      "udenu",
      "udi",
      "uzo uwani",
    ],
  },
  {
    state: "abuja",
    lgas: [
      "abaji",
      "bwari",
      "gwagwalada",
      "kuje",
      "kwali",
      "municipal area council",
    ],
  },
  {
    state: "gombe",
    lgas: [
      "akko",
      "balanga",
      "billiri",
      "dukku",
      "funakaye",
      "gombe",
      "kaltungo",
      "kwami",
      "nafada",
      "shongom",
      "yamaltu/deba",
    ],
  },
  {
    state: "imo",
    lgas: [
      "aboh mbaise",
      "ahiazu mbaise",
      "ehime mbano",
      "ezinihitte",
      "ideato north",
      "ideato south",
      "ihitte/uboma",
      "ikeduru",
      "isiala mbano",
      "isu",
      "mbaitoli",
      "ngor okpala",
      "njaba",
      "nkwerre",
      "nwangele",
      "obowo",
      "oguta",
      "ohaji/egbema",
      "okigwe",
      "orlu",
      "orsu",
      "oru east",
      "oru west",
      "owerri municipal",
      "owerri north",
      "owerri west",
      "unuimo",
    ],
  },
  {
    state: "jigawa",
    lgas: [
      "auyo",
      "babura",
      "biriniwa",
      "birnin kudu",
      "buji",
      "dutse",
      "gagarawa",
      "garki",
      "gumel",
      "guri",
      "gwaram",
      "gwiwa",
      "hadejia",
      "jahun",
      "kafin hausa",
      "kazaure",
      "kiri kasama",
      "kiyawa",
      "kaugama",
      "maigatari",
      "malam madori",
      "miga",
      "ringim",
      "roni",
      "sule tankarkar",
      "taura",
      "yankwashi",
    ],
  },
  {
    state: "kaduna",
    lgas: [
      "birnin gwari",
      "chikun",
      "giwa",
      "igabi",
      "ikara",
      "jaba",
      "jema'a",
      "kachia",
      "kaduna north",
      "kaduna south",
      "kagarko",
      "kajuru",
      "kaura",
      "kauru",
      "kubau",
      "kudan",
      "lere",
      "makarfi",
      "sabon gari",
      "sanga",
      "soba",
      "zangon kataf",
      "zaria",
    ],
  },
  {
    state: "kano",
    lgas: [
      "ajingi",
      "albasu",
      "bagwai",
      "bebeji",
      "bichi",
      "bunkure",
      "dala",
      "dambatta",
      "dawakin kudu",
      "dawakin tofa",
      "doguwa",
      "fagge",
      "gabasawa",
      "garko",
      "garun mallam",
      "gaya",
      "gezawa",
      "gwale",
      "gwarzo",
      "kabo",
      "kano municipal",
      "karaye",
      "kibiya",
      "kiru",
      "kumbotso",
      "kunchi",
      "kura",
      "madobi",
      "makoda",
      "minjibir",
      "nasarawa",
      "rano",
      "rimin gado",
      "rogo",
      "shanono",
      "sumaila",
      "takai",
      "tarauni",
      "tofa",
      "tsanyawa",
      "tudun wada",
      "ungogo",
      "warawa",
      "wudil",
    ],
  },
  {
    state: "katsina",
    lgas: [
      "bakori",
      "batagarawa",
      "batsari",
      "baure",
      "bindawa",
      "charanchi",
      "dandume",
      "danja",
      "dan musa",
      "daura",
      "dutsi",
      "dutsin ma",
      "faskari",
      "funtua",
      "ingawa",
      "jibia",
      "kafur",
      "kaita",
      "kankara",
      "kankia",
      "katsina",
      "kurfi",
      "kusada",
      "mai'adua",
      "malumfashi",
      "mani",
      "mashi",
      "matazu",
      "musawa",
      "rimi",
      "sabuwa",
      "safana",
      "sandamu",
      "zango",
    ],
  },
  {
    state: "kebbi",
    lgas: [
      "aleiro",
      "arewa dandi",
      "argungu",
      "augie",
      "bagudo",
      "birnin kebbi",
      "bunza",
      "dandi",
      "fakai",
      "gwandu",
      "jega",
      "kalgo",
      "koko/besse",
      "maiyama",
      "ngaski",
      "sakaba",
      "shanga",
      "suru",
      "wasagu/danko",
      "yauri",
      "zuru",
    ],
  },
  {
    state: "kogi",
    lgas: [
      "adavi",
      "ajaokuta",
      "ankpa",
      "bassa",
      "dekina",
      "ibaji",
      "idah",
      "igalamela odolu",
      "ijumu",
      "kabba/bunu",
      "kogi",
      "lokoja",
      "mopa muro",
      "ofu",
      "ogori/magongo",
      "okehi",
      "okene",
      "olamaboro",
      "omala",
      "yagba east",
      "yagba west",
    ],
  },
  {
    state: "kwara",
    lgas: [
      "asa",
      "baruten",
      "edu",
      "ekiti, kwara state",
      "ifelodun",
      "ilorin east",
      "ilorin south",
      "ilorin west",
      "irepodun",
      "isin",
      "kaiama",
      "moro",
      "offa",
      "oke ero",
      "oyun",
      "pategi",
    ],
  },
  {
    state: "lagos",
    lgas: [
      "agege",
      "ajeromi-ifelodun",
      "alimosho",
      "amuwo-odofin",
      "apapa",
      "badagry",
      "epe",
      "eti osa",
      "ibeju-lekki",
      "ifako-ijaiye",
      "ikeja",
      "ikorodu",
      "kosofe",
      "lagos island",
      "lagos mainland",
      "mushin",
      "ojo",
      "oshodi-isolo",
      "shomolu",
      "surulere, lagos state",
    ],
  },
  {
    state: "nasarawa",
    lgas: [
      "akwanga",
      "awe",
      "doma",
      "karu",
      "keana",
      "keffi",
      "kokona",
      "lafia",
      "nasarawa",
      "nasarawa egon",
      "obi",
      "toto",
      "wamba",
    ],
  },
  {
    state: "niger",
    lgas: [
      "agaie",
      "agwara",
      "bida",
      "borgu",
      "bosso",
      "chanchaga",
      "edati",
      "gbako",
      "gurara",
      "katcha",
      "kontagora",
      "lapai",
      "lavun",
      "magama",
      "mariga",
      "mashegu",
      "mokwa",
      "moya",
      "paikoro",
      "rafi",
      "rijau",
      "shiroro",
      "suleja",
      "tafa",
      "wushishi",
    ],
  },
  {
    state: "ogun",
    lgas: [
      "abeokuta north",
      "abeokuta south",
      "ado-odo/ota",
      "egbado north",
      "egbado south",
      "ewekoro",
      "ifo",
      "ijebu east",
      "ijebu north",
      "ijebu north east",
      "ijebu ode",
      "ikenne",
      "imeko afon",
      "ipokia",
      "obafemi owode",
      "odeda",
      "odogbolu",
      "ogun waterside",
      "remo north",
      "shagamu",
    ],
  },
  {
    state: "ondo",
    lgas: [
      "akoko north-east",
      "akoko north-west",
      "akoko south-west",
      "akoko south-east",
      "akure north",
      "akure south",
      "ese odo",
      "idanre",
      "ifedore",
      "ilaje",
      "ile oluji/okeigbo",
      "irele",
      "odigbo",
      "okitipupa",
      "ondo east",
      "ondo west",
      "ose",
      "owo",
    ],
  },
  {
    state: "osun",
    lgas: [
      "atakunmosa east",
      "atakunmosa west",
      "aiyedaade",
      "aiyedire",
      "boluwaduro",
      "boripe",
      "ede north",
      "ede south",
      "ife central",
      "ife east",
      "ife north",
      "ife south",
      "egbedore",
      "ejigbo",
      "ifedayo",
      "ifelodun",
      "ila",
      "ilesa east",
      "ilesa west",
      "irepodun",
      "irewole",
      "isokan",
      "iwo",
      "obokun",
      "odo otin",
      "ola oluwa",
      "olorunda",
      "oriade",
      "orolu",
      "osogbo",
    ],
  },
  {
    state: "oyo",
    lgas: [
      "afijio",
      "akinyele",
      "atiba",
      "atisbo",
      "egbeda",
      "ibadan north",
      "ibadan north-east",
      "ibadan north-west",
      "ibadan south-east",
      "ibadan south-west",
      "ibarapa central",
      "ibarapa east",
      "ibarapa north",
      "ido",
      "irepo",
      "iseyin",
      "itesiwaju",
      "iwajowa",
      "kajola",
      "lagelu",
      "ogbomosho north",
      "ogbomosho south",
      "ogo oluwa",
      "olorunsogo",
      "oluyole",
      "ona ara",
      "orelope",
      "ori ire",
      "oyo",
      "oyo east",
      "saki east",
      "saki west",
      "surulere, oyo state",
    ],
  },
  {
    state: "plateau",
    lgas: [
      "bokkos",
      "barkin ladi",
      "bassa",
      "jos east",
      "jos north",
      "jos south",
      "kanam",
      "kanke",
      "langtang south",
      "langtang north",
      "mangu",
      "mikang",
      "pankshin",
      "qua'an pan",
      "riyom",
      "shendam",
      "wase",
    ],
  },
  {
    state: "rivers",
    lgas: [
      "abua/odual",
      "ahoada east",
      "ahoada west",
      "akuku-toru",
      "andoni",
      "asari-toru",
      "bonny",
      "degema",
      "eleme",
      "emuoha",
      "etche",
      "gokana",
      "ikwerre",
      "khana",
      "obio/akpor",
      "ogba/egbema/ndoni",
      "ogu/bolo",
      "okrika",
      "omuma",
      "opobo/nkoro",
      "oyigbo",
      "port harcourt",
      "tai",
    ],
  },
  {
    state: "sokoto",
    lgas: [
      "binji",
      "bodinga",
      "dange shuni",
      "gada",
      "goronyo",
      "gudu",
      "gwadabawa",
      "illela",
      "isa",
      "kebbe",
      "kware",
      "rabah",
      "sabon birni",
      "shagari",
      "silame",
      "sokoto north",
      "sokoto south",
      "tambuwal",
      "tangaza",
      "tureta",
      "wamako",
      "wurno",
      "yabo",
    ],
  },
  {
    state: "taraba",
    lgas: [
      "ardo kola",
      "bali",
      "donga",
      "gashaka",
      "gassol",
      "ibi",
      "jalingo",
      "karim lamido",
      "kumi",
      "lau",
      "sardauna",
      "takum",
      "ussa",
      "wukari",
      "yorro",
      "zing",
    ],
  },
  {
    state: "yobe",
    lgas: [
      "bade",
      "bursari",
      "damaturu",
      "fika",
      "fune",
      "geidam",
      "gujba",
      "gulani",
      "jakusko",
      "karasuwa",
      "machina",
      "nangere",
      "nguru",
      "potiskum",
      "tarmuwa",
      "yunusari",
      "yusufari",
    ],
  },
  {
    state: "zamfara",
    lgas: [
      "anka",
      "bakura",
      "birnin magaji/kiyaw",
      "bukkuyum",
      "bungudu",
      "gummi",
      "gusau",
      "kaura namoda",
      "maradun",
      "maru",
      "shinkafi",
      "talata mafara",
      "chafe",
      "zurmi",
    ],
  },
];
export const CADRES = [
  "accountant",
  "administrative officer",
  "aerodrome engineer",
  "agricultural officer",
  "agricultural research officer",
  "agricutural engineer",
  "animal husbandry officer",
  "architect",
  "archivist",
  "auditor",
  "building officer",
  "chemical engineer",
  "civil and water engineer",
  "civil engineer",
  "clinical psychologist",
  "commercial officer",
  "community development officer",
  "computer engineer",
  "consultant (orthopaedic)",
  "consultant special grade",
  "consultant special grade ii (physician)",
  "cultural officer",
  "dental officer",
  "education officer",
  "electrical engineer",
  "engineer (elect/elect)",
  "environmental health officer",
  "environmental management officer",
  "fisheries",
  "foreign affairs officer",
  "forestry officer",
  "geologist",
  "health education officer",
  "hydrologist",
  "hydrology/hydrogeologist",
  "industrial inspector",
  "industrial officer",
  "information officer",
  "inspector of factories",
  "insurance inspector",
  "labour officer",
  "land officer",
  "land resources officer",
  "legal metrology",
  "librarian",
  "marine officer",
  "mechanical engineer",
  "med. officer (consultant family)",
  "medical consultant radiology",
  "medical imaging scientist",
  "medical lab. scientist",
  "medical officer",
  "meteorologist",
  "mines inspector",
  "nurse tutor",
  "nursing officer",
  "nutrition officer",
  "optometrist",
  "pathologist consultant",
  "petroleum engineer",
  "pharmacist",
  "physiotherapist",
  "planning officer",
  "population programe officer",
  "procurement officer",
  "produce officer",
  "prog. analyst",
  "psychiatrist (consultant)",
  "quantity surveyor",
  "registrar (trade marks)",
  "registrar of co-operative societies",
  "scientific officer",
  "scientific officer (fed. min. of agriculture & food security)",
  "scientific officer (fed. min. of environment)",
  "scientific officer (fed. min. of innovation, science & technology)",
  "scientific officer (fed. min. of regional development)",
  "scientific officer (health & social welfare)",
  "scientific officer (min. of defence)",
  "scientific officer (min. of solid minerals)",
  "scientific officer (min. of steel development)",
  "scientific officer (min. of water resources)",
  "skills dev. and certification officer",
  "social welfare officer",
  "sports officer",
  "state counsel",
  "statistician",
  "structural engineer",
  "surveyor",
  "tourism officer",
  "town planning",
  "veterinary officer",
  "water engineer",
  "youth development officer",
];
